### ISSUE TITLE
Add prerelease to output

### ISSUE THREAD

**Issue by xin-hedera** [terradatum/semver-action#6]
**Is your feature request related to a problem? Please describe.**

Our release workflow have conditional steps depends on whether the current version has prerelease or not.

**Describe the solution you'd like**

Add prerelease to the action output

**Describe alternatives you've considered**

**Additional context**

**Comment by rbellamy** [comment]
So something similar to the SNAPSHOT processing?

**Comment by xin-hedera** [comment]
Basically add a prerelease field to the outputs. For example, for the input 0.1.2-rc1, the prerelease should be -rc1

**Comment by rbellamy** [comment]
Of course, that makes perfect sense. Thank you for the suggestion.

**Comment by rbellamy** [comment]
I built this tool to support SNAPSHOT versions because I work with Maven repositories.

From the section in semantic versioning on [pre-release](https://semver.org/#spec-item-9):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

**Comment by rbellamy** [comment]
Sorry for the whiplash - didn't mean to close this yet.
